-- MySQL Script generated by MySQL Workbench
-- Sun May 10 20:29:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owners` (
  `id` BIGINT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `birth_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smart_homes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`smart_homes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(250) NOT NULL,
  `owner_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_smart_homes_owners_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_smart_homes_owners`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owners` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `area_sq_meters` DOUBLE NOT NULL,
  `smart_home_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rooms_smart_homes_idx` (`smart_home_id` ASC) VISIBLE,
  CONSTRAINT `fk_rooms_smart_homes`
    FOREIGN KEY (`smart_home_id`)
    REFERENCES `mydb`.`smart_homes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NULL,
  `is_online` TINYINT(1) NOT NULL,
  `installed_at` DATETIME NULL,
  `room_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devices_rooms_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_devices_rooms`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`thermostats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`thermostats` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `target_temperature` DOUBLE NOT NULL,
  `current_temperature` DOUBLE NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thermostats_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_thermostats_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smart_locks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`smart_locks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_locked` TINYINT(1) NOT NULL,
  `access_code` VARCHAR(50) NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_smart_locks_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_smart_locks_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cameras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cameras` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `resolution` INT NOT NULL,
  `is_recording` TINYINT(1) NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cameras_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_cameras_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smart_lights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`smart_lights` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `brightness` INT NOT NULL,
  `color` VARCHAR(50) NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_smart_lights_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_smart_lights_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`energy_meters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`energy_meters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `current_usage_kw` DOUBLE NOT NULL,
  `total_usage_kwh` DOUBLE NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_energy_meters_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_energy_meters_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`device_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`device_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(25) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_logs_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_device_logs_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `turn_on_time` TIME NOT NULL,
  `turn_off_time` TIME NOT NULL,
  `start_date` DATE NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `device_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_devices_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_devices`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
